Changes to StoreInvoice client and result
nodeless-io/nodeless-php pull request #1
Opened 2023-01-10 16:05 UTC by ndeet

- add invoice status to client
- specific classes for QRCode types
- amount as string and addding currency on createInvoice

2023-01-10 16:10 UTC, utxo-one requested changes

2023-01-10 16:10 UTC, utxo-one commented on src/Client/StoreInvoice.php
> +use NodelessIO\Result\StoreInvoice as ResultStoreInvoice;
Let's follow the Laravel convention and always put the "type" at the end, so StoreInvoiceResult, same on other methods.

2023-01-10 16:11 UTC, utxo-one commented on src/Client/StoreInvoice.php
> +use NodelessIO\Result\StoreInvoice as ResultStoreInvoice;
In fact I think Response is a better word than Result, what do you think?

2023-01-12 11:03 UTC, ndeet commented on src/Client/StoreInvoice.php
> +use NodelessIO\Result\StoreInvoice as ResultStoreInvoice;
Yeah sounds better, so the class is then `StoreInvoiceResponse` and the namespace is `NodelessIO\Response`?

Should I do the same for the client classes so the classname becomes `StoreInvoiceClient`?

2023-01-12 13:47 UTC, utxo-one commented on src/Client/StoreInvoice.php
> +use NodelessIO\Result\StoreInvoice as ResultStoreInvoice;
Yes to both please

2023-01-13 09:09 UTC, ndeet commented on src/Client/StoreInvoice.php
> +use NodelessIO\Result\StoreInvoice as ResultStoreInvoice;
Changed and also adjusted to latest merges on checkoutLink and fiat support.

2023-01-13 10:14 UTC, utxo-one approved these changes

2023-01-13 10:14 UTC, merged